### PR TITLE
Making Bansa more Java-friendly

### PR DESCRIPTION
**Pull request by clemp6r**
Hi,

Bansa is not really Java friendly. Being Java friendly is important because Kotlin was created for mixed environments, with the best Java interoperability as possible.

Some reasons it's not:
- store.dispatch is not a function from Java point of view. So no `store.dispatch(action);` but instead `s.getDispatch().invoke(action)`
- usage of global functions to apply middlewares or create a store. e.g a factory method should be preferred to create a store, something like `Bansa.createStore()`
- a heavy-functional approach for creating middlewares. Having a `Middleware` interface, very easy to implement from Kotlin and Java would be preferable.

I created this branch to address some of these problems and to share my point of view.

I know you're in the middle of an important refactoring (cf. pending PR), so don't merge it now, let's start a discussion here, and I will update the branch accordingly when the code base is more stable.

### CODE REVIEW

**Comment by brianegan** [comment]
Hey, great call. What do you think of even implementing Bansa in Java instead of Kotlin? I'm trying to remove as many dependencies as possible given how simply this library is, esp. in the context of Android and method count being a factor. Not only would this of course make it more Java friendly (While we could keep  a nice Kotlin inteface in mind as well), but it would also remove the Kotlin stlib + runtime as well. Could be a win/win. Thoughts?

**Comment by clemp6r** [comment]
I have mixed feelings. There is no need to write in Java to be Java friendly, it's only a matter of good practices to follow. The Kotlin lib size could be a good reason to remove it, but I think it's not that big (that's why it's popular on Android). Also, I think its more fun to write Kotlin :smile:. So not really win/win from my point of view.

I let you decide, also it could be good to get advice from other people.

**Comment by brianegan** [comment]
"Also, I think its more fun to write Kotlin" -- Hah, I know that feeling! Thanks for the feedback. I'll ask around a bit :)

**Comment by tilal6991** [comment]
I agree that  it should be written in Java. We want this library to be the Redux of the JVM and the best way to do that is with the least amount of dependencies. Otherwise somewhere down the line, someone will want a more lean library which just ends up leading to fragmentation.

**Comment by brianegan** [comment]
@tilal6991 Yah exactly. In fact, I'm wondering whether it makes sense to even merge this project with something like https://github.com/trikita/jedux. It's such a simple little lib I'd hate to see fragmentation in this space so quickly.

**Comment by clemp6r** [comment]
There is also: https://github.com/glung/redux-java
It is written in Java, but it may be rewritten in Kotlin (see: https://github.com/glung/redux-java/pull/13)

**Comment by brianegan** [comment]
Hah, yep! He's actually my coworker and  generally great dude. I simply wrote this version of Redux for my own learning :) But now I'm taking the best parts of redux-java, bansa, and jedux to combine them into a single lib that has:

  - Low method count (Missing from bansa due to kotlin requirement)
  - Support for Middleware (Missing from redux-java)
  - Well Tested (missing from jedux)
  - Dev Tools (redux-java has this, others do not)
  - Good Java & Kotlin Interfaces (redux-java / jedux are good at this, bansa not so much)

I've started a lot of this work on this branch: https://github.com/brianegan/bansa/tree/bansa-java

Be great if you could check it out and let me know what you think of that work so far!

**Pull request closed without merging**
